services:
  mysql:
    image: mysql:8-debian
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    volumes:
      - ./mysql/conf.d/:/etc/mysql/conf.d/
      - ./mysql/initializers/:/docker-entrypoint-initdb.d/
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper    
  maxwelld:
    image: zendesk/maxwell
    command: 'bin/maxwell --user=maxwell --password=P@ssw0rd --host=mysql --producer=kafka --kafka.bootstrap.servers=kafka:9092 --kafka_topic=maxwell'
    depends_on:
      - mysql
      - kafka
  kafka_stream_processor:
    build: ./cdc-processor
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - KAFKA_TOPIC=maxwell
    volumes:
      - ./cdc-processor/log/:/opt/cdc-processor/log/
    depends_on:
      - kafka
  app:
    build: ./crud-specialist
    environment:
      - DB_USER=app-user
      - DB_PASSWORD=P@ssw0rd
    depends_on:
      - mysql
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
